version: "3.1"

services:

#### DATABASES ####

  postgres:
    image: postgres
    container_name: dev_postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "984rt823ryw9"
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/data

  #mysql:
  #  image: mysql
  #  container_name: dev_mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  volumes: 
  #    - ./data-mysql:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: "984rt823ryw9"
  #    MYSQL_DATABASE: "standard"
  #  ports:
  #    - "3306:3306"

  mongo:
    image: mongo
    container_name: dev_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 984rt823ryw9
    ports:
      - 27017:27017
    volumes:
      - ./data-mongo:/data/db

#### CACHE ####

  redis:
    image: redis
    container_name: dev_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 984rt823ryw9

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dev_redis_commander
    ports:
      - "8021:8081"
    environment:
      REDIS_HOSTS: redis
      REDIS_HOST: redis
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: 984rt823ryw9


#### BUS ####

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: dev_kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: dev_kafdrop
    depends_on:
      - kafka
    #restart: on-failure
    ports:
      - "8011:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: dev_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000