version: "3.1"

services:

  postgres:
    image: postgres
    container_name: dev_postgres
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/data